import type { Metadata } from "next";
import { Geist, Plus_Jakarta_Sans } from "next/font/google";

import "./globals.css";

const fontSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontTitle = Plus_Jakarta_Sans({
  variable: "--font-title",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontTitle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
