import Head from "next/head";

import { useQuery } from "@tanstack/react-query";

import { Button } from "~/components/ui/button";

const getTest = async () => {
  try {
    const response = await fetch("http://localhost:5000/example/test", {
      headers: {
        "Content-Type": "application/json",
      },
    });
    if (!response.ok) throw new Error("Error fetching test");
    const result = await response.json();
    return result;
  } catch (error) {
    if (error instanceof Error) throw new Error(error?.message);
    else throw new Error("Error fetching test");
  }
};

export default function Home() {
  const { data: testData } = useQuery({ queryKey: ["test"], queryFn: getTest });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid items-center justify-center">
        <p>Hello world!</p>
        <h1>Hello world!</h1>

        <pre>{JSON.stringify(testData, null, 2)}</pre>

        <Button onClick={() => alert("Halo")}>Test</Button>
      </div>
    </>
  );
}
